In [1]:
import pandas as pd
import yaml

In [2]:
"""Load configuration"""
with open("/home/trduong/Data/counterfactual_fairness_game_theoric/configuration.yml", 'r') as stream:
    try:
        conf = yaml.safe_load(stream)
    except yaml.YAMLError as exc:
        print(exc)

In [3]:
df = pd.read_csv(conf['result_law'])

In [4]:
df

,race,sex,LSAT,UGPA,ZFYA,full_prediction,unaware_prediction,cf_prediction,inv_prediction
0,1,0,0.374797,-0.328945,-1.216912,0.063242,0.049148,-0.082521,-0.000379
1,1,0,-0.186888,-0.571182,-0.059365,-0.058810,-0.116302,0.007656,0.003960
2,1,1,-1.310258,-0.328945,-0.535366,-0.196115,-0.356468,-0.428630,-0.001729
3,1,0,0.000341,0.397765,-1.519822,0.071920,0.049746,-0.044159,-0.000215
4,1,0,-1.216644,0.882239,0.167817,-0.090202,-0.182710,-0.170610,0.003155
...,...,...,...,...,...,...,...,...,...
19562,1,1,-0.748573,1.851186,0.741182,0.122401,0.050941,0.099575,-0.029482
19563,1,0,0.187569,1.124476,-0.405547,0.178092,0.185549,0.078944,-0.000766
19564,1,0,-0.186888,1.851186,2.136730,0.186770,0.186146,0.150676,-0.010951
19565,1,1,-1.123030,-0.813419,0.167817,-0.212733,-0.371890,-0.240161,-0.007356
19566,1,1,-1.684715,-0.328945,0.124544,-0.261111,-0.446605,-0.167793,-0.017152

In [5]:
df = pd.read_csv(conf['result_evaluate_law'])

In [6]:
df

               method      RMSE       MAE  sinkhorn    energy  gaussian
0     full_prediction  0.938627  0.755647  0.323727  0.446445  0.082774
1  unaware_prediction  0.955065  0.767867  0.058061  0.102386  0.031875
2       cf_prediction  0.988616  0.794960  0.001922  0.007145  0.009748
3      inv_prediction  0.999988  0.804971  0.000010  0.000126  0.001109

In [7]:
method_name = {
    "full_prediction" : "Full model",
    "unaware_prediction" : "Unawareness model",
    "cf_prediction" : "Counterfactual Fairness model",
    "inv_prediction": "Invariant model"
    
}

In [8]:
df['method'] = df['method'].map(method_name)

In [11]:
df = pd.read_csv("/home/trduong/Data/counterfactual_fairness_game_theoric/reports/results/law.csv")

In [12]:
df

,race,sex,LSAT,UGPA,ZFYA,full_prediction,unaware_prediction,cf_prediction,inv_prediction
0,1,0,0.374797,-0.328945,-1.216912,0.063242,0.049148,-0.082521,-0.000379
1,1,0,-0.186888,-0.571182,-0.059365,-0.058810,-0.116302,0.007656,0.003960
2,1,1,-1.310258,-0.328945,-0.535366,-0.196115,-0.356468,-0.428630,-0.001729
3,1,0,0.000341,0.397765,-1.519822,0.071920,0.049746,-0.044159,-0.000215
4,1,0,-1.216644,0.882239,0.167817,-0.090202,-0.182710,-0.170610,0.003155
...,...,...,...,...,...,...,...,...,...
19562,1,1,-0.748573,1.851186,0.741182,0.122401,0.050941,0.099575,-0.029482
19563,1,0,0.187569,1.124476,-0.405547,0.178092,0.185549,0.078944,-0.000766
19564,1,0,-0.186888,1.851186,2.136730,0.186770,0.186146,0.150676,-0.010951
19565,1,1,-1.123030,-0.813419,0.167817,-0.212733,-0.371890,-0.240161,-0.007356
19566,1,1,-1.684715,-0.328945,0.124544,-0.261111,-0.446605,-0.167793,-0.017152